2025-05-13 11:37:01: ERROR | dih | '1f34c6eb949d36057eb3be58107b7985732f2f09a319f480e45eaa4b7a1c630e': Llamada a la función 'accion_confidencial' con parámetros: user='dih' -> Resultado: Acceso denegado: usuario desconocido 'dih' |
